/**
 * Manages user prompts and confirmations for AI code annotation.
 */

import * as vscode from 'vscode';
import { AnnotationMetadata } from './types';

export class PromptManager {
  /**
   * Show the main AI confirmation dialog.
   */
  static async promptForAIConfirmation(): Promise<boolean> {
    const response = await vscode.window.showQuickPick(['Yes', 'No'], {
      placeHolder: 'Was this code generated using AI?',
      title: 'AI-Generated Code Detection',
      canPickMany: false,
    });

    return response === 'Yes';
  }

  /**
   * Collect annotation metadata from the user.
   */
  static async collectMetadata(
    defaultAuthorId: string,
    defaultTool: string
  ): Promise<AnnotationMetadata | null> {
    // Get tool name
    const toolName = await vscode.window.showInputBox({
      placeHolder: 'e.g., GitHub Copilot, GPT-4, Claude',
      prompt: 'AI Tool Name:',
      value: defaultTool,
      validateInput: (value) => {
        if (!value.trim()) {
          return 'Tool name is required';
        }
        return null;
      },
    });

    if (!toolName) {
      return null;
    }

    // Get optional tool version
    const toolVersion = await vscode.window.showInputBox({
      placeHolder: 'Optional, e.g., 1.0.0',
      prompt: 'AI Tool Version (optional):',
    });

    // Get author ID
    const authorId = await vscode.window.showInputBox({
      placeHolder: 'e.g., dev-001, john.doe',
      prompt: 'Developer ID/Author ID:',
      value: defaultAuthorId,
      validateInput: (value) => {
        if (!value.trim()) {
          return 'Author ID is required';
        }
        return null;
      },
    });

    if (!authorId) {
      return null;
    }

    return {
      toolName: toolName.trim(),
      toolVersion: toolVersion?.trim() || undefined,
      date: new Date().toISOString(),
      authorId: authorId.trim(),
      action: 'GENERATED',
    };
  }

  /**
   * Show an error dialog with validation errors.
   */
  static showValidationError(errors: string[]): void {
    const message = `Cannot annotate code:\n${errors.join('\n')}`;
    vscode.window.showErrorMessage(message);
  }

  /**
   * Show a confirmation before wrapping code.
   */
  static async confirmAnnotation(toolName: string, authorId: string): Promise<boolean> {
    const response = await vscode.window.showInformationMessage(
      `Annotate as generated by ${toolName} (${authorId})?`,
      { modal: false },
      'Yes',
      'No'
    );
    return response === 'Yes';
  }
}
